---
- name: "Mount tasks"
  when:
    - nfs_mount is defined
    - nfs_mount | length > 0
  block:
    - name: "Install nfs-common package"
      ansible.builtin.package:
        name: "nfs-common"
        state: present
      #when: ansible_os_family == 'Debian'
      when: ansible_distribution == "Debian"

    #- name: "Find mount point on fstab"
    #  ansible.builtin.command: "cat /etc/fstab"
    #  register: content
    #  changed_when: false

    - name: "Create mount point directories"
      ansible.builtin.file:
        path: "{{ item.nfs_folder }}"
        state: directory
        mode: '0755'
      with_items: "{{ nfs_mount }}"

    - name: "Mount nfs share and add it to /etc/fstab"
      ansible.posix.mount:
        src: "{{ item.nfs_server }}"
        path: "{{ item.nfs_folder }}"
        fstype: nfs
        opts: "{{ item.nfs_opts | default(omit) }}"
        state: mounted
      with_items: "{{ nfs_mount }}"
